// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGpf1cSVKDw8r1rRkTvA-_UCsxUlxP8Jk',
    appId: '1:971678292113:web:4d0f7f514c34bce9d68730',
    messagingSenderId: '971678292113',
    projectId: 'studymate-9c128',
    authDomain: 'studymate-9c128.firebaseapp.com',
    storageBucket: 'studymate-9c128.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBMsJXFjU0h0kmzdRwBW0pYzx_JnHq_s',
    appId: '1:971678292113:android:4ea9532496149437d68730',
    messagingSenderId: '971678292113',
    projectId: 'studymate-9c128',
    storageBucket: 'studymate-9c128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfhtEgM9UbcjR3E2IKE1I8uewQlq_AKSg',
    appId: '1:971678292113:ios:2b32c3731780916cd68730',
    messagingSenderId: '971678292113',
    projectId: 'studymate-9c128',
    storageBucket: 'studymate-9c128.firebasestorage.app',
    androidClientId: '971678292113-79abo9isov3rt3adbnuj6ei31difui95.apps.googleusercontent.com',
    iosClientId: '971678292113-0jrs4l6slqdrpb5n34ls8707kip6uqmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfhtEgM9UbcjR3E2IKE1I8uewQlq_AKSg',
    appId: '1:971678292113:ios:2b32c3731780916cd68730',
    messagingSenderId: '971678292113',
    projectId: 'studymate-9c128',
    storageBucket: 'studymate-9c128.firebasestorage.app',
    androidClientId: '971678292113-79abo9isov3rt3adbnuj6ei31difui95.apps.googleusercontent.com',
    iosClientId: '971678292113-0jrs4l6slqdrpb5n34ls8707kip6uqmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGpf1cSVKDw8r1rRkTvA-_UCsxUlxP8Jk',
    appId: '1:971678292113:web:dc934f7b9887e85cd68730',
    messagingSenderId: '971678292113',
    projectId: 'studymate-9c128',
    authDomain: 'studymate-9c128.firebaseapp.com',
    storageBucket: 'studymate-9c128.firebasestorage.app',
  );

}